require: sudo
language: node_js
services:
  - docker
env:
  - DOCKER_IMAGE=prodest/api-transparencia SERVICE_NAME=api-transparencia RANCHER_URL=http://cloud.datacenter.es.gov.br.local/v1/projects/1a4680 RANCHER_STACK=api RANCHER_COMPOSE_URL=http://cloud.datacenter.es.gov.br.local/v1/projects/1a4680/environments/1e56/composeconfig
script:
  /bin/sh .travis.sh
deploy:
  provider: script
  script: /bin/sh .deploy.sh
  on:
    branch: master
